# Generated by Django 3.1.4 on 2021-01-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
    ]
